### ISSUE TITLE
Updating assemblyscript

### ISSUE THREAD

**Issue by munrocket** [surma/rollup-plugin-assemblyscript#4]
If your repo has an updated assemblyscript, this plugin is still using the old version.

**Comment by surma** [comment]
You are right. I should be declaring AssemblyScript as a peer dependency. Do you wanna whip up a PR?

**Comment by munrocket** [comment]
Thanks created a PR.

I also created simple support for .as and test example for checking in another PR #3. Nothing too smart and without CI.
